# Generated by Django 2.0.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos_prenom', '0002_auto_20190403_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentacion',
            options={'verbose_name': 'alimentación', 'verbose_name_plural': 'alimentaciones'},
        ),
        migrations.AlterModelOptions(
            name='trabajoextraordinario',
            options={'verbose_name_plural': 'trabajos extraordinarios'},
        ),
        migrations.AlterModelOptions(
            name='vacaciones',
            options={'verbose_name_plural': 'vacaciones'},
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='cant_dias',
            field=models.PositiveIntegerField(verbose_name='días trabajados'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='cant_dias_dieta',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='días dieta'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='codigo_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador', verbose_name='trabajador'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='desde',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='hasta',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='trabajoextraordinario',
            name='cant_horas',
            field=models.PositiveIntegerField(verbose_name='cantidad de horas'),
        ),
        migrations.AlterField(
            model_name='trabajoextraordinario',
            name='codigo_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador', verbose_name='trabajador'),
        ),
        migrations.AlterField(
            model_name='trabajoextraordinario',
            name='desde',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='trabajoextraordinario',
            name='hasta',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='cant_dias',
            field=models.PositiveIntegerField(verbose_name='cantidad de días'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='codigo_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador', verbose_name='trabajador'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='desde',
            field=models.DateField(verbose_name='fecha inicio'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='director',
            field=models.CharField(max_length=60, verbose_name='aprobado por'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='fecha',
            field=models.DateField(verbose_name='fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='hasta',
            field=models.DateField(verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='horas',
            field=models.PositiveIntegerField(verbose_name='cantidad de horas a descontar'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='horas1',
            field=models.PositiveIntegerField(default=0, verbose_name='cantidad de horas a descontar mes próximo'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='incorporacion',
            field=models.DateField(verbose_name='fecha de inincorporación'),
        ),
        migrations.AlterField(
            model_name='vacaciones',
            name='jefe_area',
            field=models.CharField(max_length=60, verbose_name='jefe de área'),
        ),
    ]
