# Generated by Django 2.0.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20201019_0818'),
        ('entrada_datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.Departamento'),
            preserve_default=False,
        ),
    ]
