# Generated by Django 2.0.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20201019_0818'),
        ('plantilla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantilla',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report']},
        ),
        migrations.AddField(
            model_name='plantilla',
            name='escala_salarial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.EscalaSalarial'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla', to='adm.Cargo'),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Departamento'),
        ),
        migrations.RemoveField(
            model_name='plantilla',
            name='unidad',
        ),
        migrations.AlterUniqueTogether(
            name='plantilla',
            unique_together={('departamento', 'cargo', 'escala_salarial')},
        ),
    ]
