# Generated by Django 2.0.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ges_trab', '0005_auto_20201019_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCapacitacion',
            fields=[
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='código')),
                ('institucion', models.CharField(blank=True, max_length=150, null=True, verbose_name='institución')),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('profesor', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_term', models.DateTimeField(null=True)),
                ('horas', models.PositiveIntegerField(null=True)),
                ('valor_mn', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('valor_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'actividad capacitación',
                'verbose_name_plural': 'actividades capacitación',
                'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'],
            },
        ),
        migrations.CreateModel(
            name='ActividadCapacitacionTrabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.CharField(max_length=30, null=True, verbose_name='evaluación')),
                ('tomo', models.CharField(max_length=20, null=True)),
                ('folio', models.CharField(max_length=20, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.ActividadCapacitacion')),
                ('trabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ges_trab.Trabajador')),
            ],
            options={
                'verbose_name': 'actividad capacitación trabajadores',
                'verbose_name_plural': 'actividades capacitación trabajadores',
                'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'],
            },
        ),
        migrations.CreateModel(
            name='ModoFormacion',
            fields=[
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='código')),
            ],
            options={
                'verbose_name': 'modo de formación',
                'verbose_name_plural': 'modos de formación',
                'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'],
            },
        ),
        migrations.CreateModel(
            name='ModoFormacion_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=5, verbose_name='código')),
            ],
            options={
                'verbose_name': 'modo de formación',
                'verbose_name_plural': 'modos de formación',
                'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'],
            },
        ),
        migrations.CreateModel(
            name='Ponencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('premio', models.CharField(max_length=30, verbose_name='código')),
                ('instancia', models.CharField(max_length=30)),
                ('actividad_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.ActividadCapacitacionTrabajadores')),
            ],
            options={
                'verbose_name': 'ponencia',
                'verbose_name_plural': 'ponencias',
                'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'],
            },
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('nombre', models.CharField(max_length=150)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'temática',
                'verbose_name_plural': 'temáticas',
                'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'],
            },
        ),
        migrations.CreateModel(
            name='TipoActividadCapacitacion',
            fields=[
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='código')),
                ('modo_formacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.ModoFormacion')),
            ],
            options={
                'verbose_name': 'tipo de actividad',
                'verbose_name_plural': 'tipos de actividades',
                'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'],
            },
        ),
        migrations.AddField(
            model_name='actividadcapacitacion',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Tematica'),
        ),
        migrations.AddField(
            model_name='actividadcapacitacion',
            name='tipo_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.TipoActividadCapacitacion'),
        ),
    ]
