# Generated by Django 2.0.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_auto_20201019_0818'),
        ('ges_trab', '0005_auto_20201019_0818'),
        ('prenomina15', '0018_auto_20191211_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadOrganizativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='código')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantillaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_plazas', models.IntegerField(default=1, verbose_name='cantidad de plazas')),
                ('disponibles', models.IntegerField(editable=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Cargo')),
                ('escala_salarial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.EscalaSalarial')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prenomina15.EspecialidadOrganizativa')),
            ],
            options={
                'verbose_name': 'platilla para servicio',
                'verbose_name_plural': 'plantillas para servicio',
            },
        ),
        migrations.CreateModel(
            name='TrabajadorServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_plant', models.PositiveIntegerField(default=0, verbose_name='orden en la plantilla')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('por_cies', models.CharField(choices=[('1', '0%'), ('2', '30%'), ('3', '50%')], default='1', max_length=1, verbose_name='por ciento CIES')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Cargo')),
            ],
            options={
                'verbose_name': 'trabajador del servicio',
                'verbose_name_plural': 'trabajadores del servicio',
            },
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'especialidades'},
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
        migrations.AddField(
            model_name='catalogo',
            name='incumplimiento_calidad_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='valor de incumplimiento en calidad'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='incumplimiento_cpl_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='valor de incumplimiento en CPL'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='incumplimiento_plano_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='valor de incumplimiento en plano'),
        ),
        migrations.AddField(
            model_name='catalogo',
            name='valor_pen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='valor de penalización'),
        ),
        migrations.AddField(
            model_name='obra',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='etapa',
            field=models.CharField(choices=[('IB', 'IB'), ('ID', 'ID'), ('PTE D', 'PTE Decoración')], default='IB', max_length=15),
        ),
        migrations.AddField(
            model_name='plano',
            name='incumplimiento_calidad',
            field=models.IntegerField(default=0, verbose_name='incumplimiento en calidad'),
        ),
        migrations.AddField(
            model_name='plano',
            name='incumplimiento_calidad_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='valor de incumplimiento en calidad'),
        ),
        migrations.AddField(
            model_name='plano',
            name='incumplimiento_cpl',
            field=models.IntegerField(default=0, verbose_name='incumplimiento en CPL'),
        ),
        migrations.AddField(
            model_name='plano',
            name='incumplimiento_cpl_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='valor de incumplimiento en CPL'),
        ),
        migrations.AddField(
            model_name='plano',
            name='incumplimiento_plano',
            field=models.IntegerField(default=0, verbose_name='incumplimiento en plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='incumplimiento_plano_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='valor de incumplimiento en plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='valor_pen',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='valor de penalización'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='cant',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='porciento',
            field=models.CharField(choices=[('1.0', '100%'), ('0.7', '70%'), ('0.3', '30%')], default='', max_length=3, verbose_name='por ciento de detalle'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='lc',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='listado de cantidades'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='md',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='memoria descriptiva'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='pr',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4, verbose_name='presupuesto'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='codigo',
            field=models.CharField(max_length=2, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='obra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Obra', verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='gesc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='adm.EscalaSalarial', verbose_name='grupo escala'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='horas_a2',
            field=models.PositiveIntegerField(verbose_name='horas A2'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='orden_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='entrada_datos.OT', verbose_name='orden de trabajo'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='owner',
            field=models.CharField(default='admin', editable=False, max_length=20, verbose_name='dueño'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('OT', 'Obra Turismo'), ('VT', 'Vivienda para Turismo'), ('R6', 'Resolucion 6')], default='', max_length=2, verbose_name='tipo de servicio'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='cant',
            field=models.PositiveIntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='estado',
            field=models.CharField(choices=[('SR', 'SR'), ('V', 'V'), ('GE', 'GE'), ('VPC', 'VPC')], default='SR', editable=False, max_length=3, verbose_name='estado del plano'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='fecha_fin',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='fecha_ini',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='fecha_pago',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='fecha de pago'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='fecha_vpc',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='fecha VPC'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='last_rev',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='última revision'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='num',
            field=models.CharField(max_length=5, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='obra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Obra', verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='porciento',
            field=models.CharField(choices=[('1.0', '100%'), ('0.7', '70%'), ('0.3', '30%')], default='', max_length=3, verbose_name='por ciento de detalle'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tipo_doc',
            field=models.CharField(choices=[('PL', 'PL'), ('MD', 'MD'), ('LC', 'LC'), ('PR', 'PR')], default='PL', max_length=2, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='trabajador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='ges_trab.Trabajador'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='vpc',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', editable=False, max_length=2, verbose_name='VPC'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='fecha_revision',
            field=models.DateField(verbose_name='fecha de revisión'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='fecha_vpc',
            field=models.DateField(blank=True, null=True, verbose_name='fecha VPC'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='no_rev',
            field=models.IntegerField(editable=False, verbose_name='número de revisión'),
        ),
        migrations.AlterField(
            model_name='salariomax',
            name='grupo_esc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.EscalaSalarial', verbose_name='grupo escala'),
        ),
        migrations.AlterField(
            model_name='salariomax',
            name='sal',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='salario'),
        ),
        migrations.AlterField(
            model_name='salariomax',
            name='tipo',
            field=models.CharField(choices=[('OT', 'Obra Turismo'), ('VT', 'Vivienda para Turismo')], default='', max_length=2, verbose_name='tipo de servicio'),
        ),
        migrations.AddField(
            model_name='trabajadorservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prenomina15.Obra'),
        ),
        migrations.AddField(
            model_name='trabajadorservicio',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ges_trab.Trabajador'),
        ),
        migrations.AddField(
            model_name='plantillaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prenomina15.Obra'),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='especialidad_organizativa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prenomina15.EspecialidadOrganizativa'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillaservicio',
            unique_together={('servicio', 'cargo', 'escala_salarial')},
        ),
    ]
