# Generated by Django 2.0.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cant_horas',
            field=models.PositiveIntegerField(verbose_name='cantidad de horas'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='horas_ext',
            field=models.PositiveIntegerField(default=0, verbose_name='horas extras'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='orden_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.OT', verbose_name='orden de trabajo'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='prod_reportada',
            field=models.PositiveIntegerField(editable=False, verbose_name='producción reportada'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='tarifa_hor',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=7, verbose_name='tarifa horaria'),
        ),
        migrations.AlterField(
            model_name='datosanual',
            name='cant_horas',
            field=models.PositiveIntegerField(verbose_name='cantidad de horas'),
        ),
        migrations.AlterField(
            model_name='datosanual',
            name='horas_ext',
            field=models.PositiveIntegerField(default=0, verbose_name='horas extras'),
        ),
        migrations.AlterField(
            model_name='datosanual',
            name='orden_trab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.OT', verbose_name='orden de trabajo'),
        ),
        migrations.AlterField(
            model_name='datosanual',
            name='prod_reportada',
            field=models.PositiveIntegerField(editable=False, verbose_name='producción reportada'),
        ),
        migrations.AlterField(
            model_name='datosanual',
            name='prod_tecleada',
            field=models.PositiveIntegerField(default=0, verbose_name='producción tecleada'),
        ),
        migrations.AlterField(
            model_name='datosanual',
            name='tarifa_hor',
            field=models.DecimalField(decimal_places=6, editable=False, max_digits=7, verbose_name='tarifa horaria'),
        ),
    ]
