# Generated by Django 2.0.2 on 2020-10-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsidio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidio',
            name='centro',
            field=models.CharField(max_length=200, verbose_name='centro asistencial'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='codigo_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador', verbose_name='trabajador'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='desde',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='diagnostico',
            field=models.CharField(max_length=80, verbose_name='diagnóstico'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='dias',
            field=models.PositiveIntegerField(verbose_name='cantidad de días a pagar'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='ent_72',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default=('Si', 'Si'), max_length=2, verbose_name='entregado antes de las 72 horas'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='fecha',
            field=models.DateField(verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='hasta',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='medico',
            field=models.CharField(max_length=200, verbose_name='nombre del médico'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='no_reg',
            field=models.PositiveIntegerField(default=1, verbose_name='número de registro del certificado'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='por_ciento',
            field=models.CharField(choices=[('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default=('50', '50'), max_length=3, verbose_name='por ciento a pagar'),
        ),
        migrations.AlterField(
            model_name='subsidio',
            name='tipo',
            field=models.CharField(choices=[('Inic.', 'Inicial'), ('Cont.', 'Continuado')], default=('Inic.', 'Inicial'), max_length=5, verbose_name='tipo de certificado'),
        ),
    ]
