# Generated by Django 2.0.2 on 2020-10-19 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0001_initial'),
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaSalarialReforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=8, unique=True)),
                ('coeficiente', models.DecimalField(decimal_places=15, max_digits=16, validators=[django.core.validators.MinValueValidator(0, 'Valor inválido. El valor debe ser mayor o igual que 0.')])),
                ('salario_escala', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0, 'Valor inválido. El valor debe ser mayor o igual que 0.')])),
            ],
            options={
                'verbose_name': 'escala salarial reforma',
                'verbose_name_plural': 'escalas salariales reforma',
            },
        ),
        migrations.AlterModelOptions(
            name='antiguedad',
            options={'default_permissions': ['read', 'add', 'delete', 'change'], 'verbose_name': 'antigüedad', 'verbose_name_plural': 'antigüedades'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'default_permissions': ['read', 'add', 'delete', 'change'], 'ordering': ['codigo'], 'verbose_name': 'calificación', 'verbose_name_plural': 'calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'], 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='cies',
            options={'default_permissions': ['read', 'add', 'delete', 'change'], 'verbose_name': 'CIES', 'verbose_name_plural': 'CIES'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'default_permissions': ['read', 'add', 'delete', 'change'], 'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('id'), nulls_last=True)]},
        ),
        migrations.AlterModelOptions(
            name='escalasalarial',
            options={'verbose_name_plural': 'escalas salariales'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'], 'ordering': ['codigo'], 'verbose_name_plural': 'especialidades'},
        ),
        migrations.AlterModelOptions(
            name='seccionsindical',
            options={'default_permissions': ['read', 'add', 'delete', 'change'], 'verbose_name': 'sección sindical', 'verbose_name_plural': 'secciones sindicales'},
        ),
        migrations.AlterModelOptions(
            name='unidadorg',
            options={'default_permissions': ['read', 'add', 'delete', 'change'], 'ordering': ['pk'], 'verbose_name': 'unidad organizacional', 'verbose_name_plural': 'unidades organizacionales'},
        ),
        migrations.AddField(
            model_name='departamento',
            name='cargos',
            field=models.ManyToManyField(through='plantilla.Plantilla', to='adm.Cargo'),
        ),
        migrations.AlterField(
            model_name='antiguedad',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.EscalaSalarial', verbose_name='escala salarial'),
        ),
        migrations.AlterField(
            model_name='antiguedad',
            name='porciento_5',
            field=models.BooleanField(verbose_name='pago del 5%'),
        ),
        migrations.AlterField(
            model_name='antiguedad',
            name='tecnico',
            field=models.BooleanField(verbose_name='técnico'),
        ),
        migrations.AlterField(
            model_name='antiguedad',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'Valor inválido. El valor debe ser mayor o igual que 0.')]),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='codigo',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='Debe tener exactamente dos caracteres numéricos.', regex='^[0-9]{2}$')], verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='codigo',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)], verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')]),
        ),
        migrations.AlterField(
            model_name='cies',
            name='cies',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'Valor inválido. El valor debe ser mayor o igual que 0.')], verbose_name='CIES'),
        ),
        migrations.AlterField(
            model_name='cies',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.EscalaSalarial', verbose_name='escala salarial'),
        ),
        migrations.AlterField(
            model_name='cies',
            name='porciento_30',
            field=models.BooleanField(verbose_name='pago del 30%'),
        ),
        migrations.AlterField(
            model_name='cies',
            name='tecnico',
            field=models.BooleanField(verbose_name='técnico'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Campo obligatorio. Cadena numérica de 5 dígitos', regex='^[0-9]{5}$')], verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='dirige',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamentos', to='adm.Departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')]),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.SeccionSindical', verbose_name='sección sindical'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamentos', to='adm.UnidadOrg', verbose_name='unidad organizacional'),
        ),
        migrations.AlterField(
            model_name='escalasalarial',
            name='coeficientes',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0, 'Valor inválido. El valor debe ser mayor o igual que 0.')]),
        ),
        migrations.AlterField(
            model_name='escalasalarial',
            name='salario_escala',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, 'Valor inválido. El valor debe ser mayor o igual que 0.')]),
        ),
        migrations.AlterField(
            model_name='escalasalarial',
            name='tarifa_horaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='calificacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.Calificacion', verbose_name='calificación'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='codigo',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Debe ser una cadena numérica de 8 dígitos.', regex='^[0-9]{8}$')], verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')]),
        ),
        migrations.AlterField(
            model_name='seccionsindical',
            name='nombre',
            field=models.CharField(max_length=35, unique=True, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')]),
        ),
        migrations.AlterField(
            model_name='unidadorg',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')]),
        ),
    ]
