# Generated by Django 2.0.2 on 2020-10-19 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismo', '0002_auto_20190403_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausencia',
            name='causal',
            field=models.CharField(choices=[('V', 'Vacaciones'), ('Cm', 'Certificado Médico'), ('LSS', 'Licencia sin Sueldo'), ('MI', 'Misión Internacionalista'), ('I', 'Interrupción'), ('B', 'Baja'), (('A',), 'Alta'), ('M', 'Movilización'), ('E', 'Enfermo'), ('Fr', 'Receso Laboral Retribuido'), ('F', 'Prestación Social')], default='V', max_length=3),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='codigo_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador', verbose_name='trabajador'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='fecha',
            field=models.DateField(verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='ausencia',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tarjetacnc',
            name='anno',
            field=models.PositiveSmallIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2150), django.core.validators.MinValueValidator(1900)], verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='tarjetacnc',
            name='cant_dias',
            field=models.PositiveIntegerField(verbose_name='cant. días'),
        ),
        migrations.AlterField(
            model_name='tarjetacnc',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='10', max_length=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
