# Generated by Django 2.0.2 on 2020-10-19 12:18

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rechum.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ges_trab', '0004_auto_20191210_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
            ],
            options={
                'ordering': ['departamento__codigo', 'org_plantilla'],
                'proxy': True,
                'indexes': [],
            },
            bases=('ges_trab.trabajador',),
        ),
        migrations.CreateModel(
            name='BajaOther',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ges_trab.trabajador',),
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report'], 'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterModelOptions(
            name='cpl',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report']},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report']},
        ),
        migrations.AlterModelOptions(
            name='nucleofamiliar',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report']},
        ),
        migrations.AlterModelOptions(
            name='trabajador',
            options={'default_permissions': ['read', 'add', 'delete', 'change', 'export', 'report', 'full-control'], 'verbose_name_plural': 'trabajadores'},
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='s_pago',
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='motivo_baja',
            field=models.CharField(blank=True, choices=[('01', 'Rescisión del contrato a voluntad del trabajador'), ('02', 'Motivos salariales'), ('03', 'Deficiente organización del trabajo'), ('04', 'Lejanía del centro de trabajo'), ('05', 'Inconveniencia del horario de trabajo'), ('06', 'No trabajar dentro de la especialidad'), ('07', 'Condiciones anormales de trabajo'), ('08', 'Escasa posibilidad de superación'), ('09', 'Problemas de vivienda y o ausencia de servicios sociales'), ('10', 'Inconformidad con los métodos de dirección'), ('11', 'Matrimonio atención a menores y familiares'), ('12', 'Bajas de trabajadores por sanción laboral'), ('13', 'Bajas por no reincorporarse después de cumplido el período de vacaciones o licencia no retribuida'), ('14', 'Bajas por salida del país'), ('15', 'Bajas por Jubilación'), ('16', 'Bajas por Fallecimiento'), ('17', 'Otras bajas por fluctuación')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')], verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='disponible',
            name='fecha',
            field=models.DateField(verbose_name='fecha de disponibilidad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='a_mision',
            field=models.CharField(blank=True, max_length=15, verbose_name='año de misión'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ges_trab.Actividad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='albergado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='anno_graduado',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='año de graduado'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='antiguedad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='antigüedad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='apellidos',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula y no puede contener números ni caracteres especiales.', regex='^[A-Z]{1}[A-Za-záéíóúñ .]+$')]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='calificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Calificacion', verbose_name='calificación'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Cargo', verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cat_cient',
            field=models.CharField(choices=[('1', 'Ninguna'), ('2', 'Máster'), ('3', 'Doctor')], max_length=10, verbose_name='categoría científica'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='categoria',
            field=models.CharField(choices=[('A', 'Administrativo'), ('C', 'Cuadro '), ('O', 'Operario'), ('S', 'Servicio'), ('T', 'Técnico ')], max_length=15, verbose_name='categoría ocupacional'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='centro_graduacion',
            field=models.CharField(default='Ninguno', max_length=40, verbose_name='centro de graduación'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='ci',
            field=models.CharField(max_length=11, unique=True, verbose_name='carnet de identidad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='codigo_interno',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='Código interno inválido. Código de 3 números.', regex='^[0-9]{3}$')], verbose_name='código interno'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trabajadores', to='adm.Departamento', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='derecho',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='direccion',
            field=models.CharField(max_length=500, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='enfermedades',
            field=models.CharField(blank=True, default='Ninguna', max_length=100, verbose_name='enfermedades que padece'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='escolaridad',
            field=models.CharField(choices=[('6to', '6to Grado'), ('9no ', '9no Grado'), ('12mo ', '12mo Grado'), ('TM', 'Técnico Medio'), ('OC', 'Obrero Calificado'), ('Univ', 'Universitario'), ('FOC', 'Facultad Obrero Campesino')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adm.Especialidad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero(a)'), ('Casado', 'Casado(a)'), ('Divorciado', 'Divorciado(a)'), ('Viudo', 'Viudo(a)')], default=('Soltero', 'Soltero(a)'), max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='estado_mayor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='estatura',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='etnia',
            field=models.CharField(choices=[('B', 'Blanca'), ('M', 'Mestiza'), ('N', 'Negra')], default=('B', 'Blanca'), max_length=1),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_alta',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha de alta al cargo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_contrato',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha de contrato'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_disponible',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de inicio disponibilidad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='fecha de ingreso al organismo'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_nac',
            field=models.DateField(blank=True, editable=False, null=True, validators=[rechum.validators.MinAgeValidator(15), rechum.validators.MaxAgeValidator(85)], verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blp', 'bmp', 'dib', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'apng', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'pnm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'icb', 'vda', 'vst', 'webp', 'wmf', 'emf', 'xbm', 'xpm'])]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fuerza_i',
            field=models.CharField(blank=True, choices=[('1', 'Otras Empresas'), ('2', 'Reclusos'), ('3', 'Microbrigrada'), ('4', 'Otros')], max_length=20, verbose_name='fuerza irregular'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='hijos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='cantidad de hijos'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='idioma',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='incre_res',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='pago por perfeccionamiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='j_laboral',
            field=models.BooleanField(default=False, verbose_name='jornada laboral de 208 horas'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='licencia',
            field=models.CharField(blank=True, choices=[('0', 'Primera'), ('1', 'Segunda'), ('2', 'Tercera'), ('3', 'Cuarta'), ('4', 'Quinta')], default='No procede', max_length=20, verbose_name='licencia de conducción'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=30, verbose_name='lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='militancia',
            field=models.CharField(blank=True, choices=[('1', 'UJC'), ('2', 'PCC')], max_length=5),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='motivo_alta',
            field=models.CharField(blank=True, default='Ocupar plaza vacante', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre_madre',
            field=models.CharField(blank=True, max_length=40, verbose_name='nombre de la madre'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre_padre',
            field=models.CharField(blank=True, max_length=40, verbose_name='nombre del padre'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='org_cult',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')], verbose_name='organizaciones culturales'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='org_masas',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')], verbose_name='organizaciones de masas'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='org_plantilla',
            field=models.PositiveIntegerField(verbose_name='organización en la plantilla'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='org_prof',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula, y no presentar caracteres especiales.', regex='^[A-Z]{1}[A-Za-z0-9áéíóúñ .,#\'"()]+$')], verbose_name='organizaciones profesionales'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='orga_defensa',
            field=models.CharField(choices=[('MTT', 'MTT'), ('FEI', 'FEI'), ('BPD-LR ', 'BPD-LR'), ('BPD-PTG ', 'BPD-PTG'), ('U/R', 'U/R'), ('Imp', 'Imprescindible')], max_length=20, verbose_name='organización en la defensa'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='peso',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='por_anti',
            field=models.CharField(choices=[('0', '0%'), ('1', '5%'), ('2', '10%')], default=('0', '0%'), max_length=3, verbose_name='% antigüedad'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='primer_nombre',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula y no puede contener números ni caracteres especiales.', regex='^[A-Z]{1}[A-Za-záéíóúñ .]+$')]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='residencia',
            field=models.CharField(max_length=20, verbose_name='municipio de residencia'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sal_bas',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='salario básico'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sal_cat_cient',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='salario por cat. científica'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sal_cond_anor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='salario condiciones anormales'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sal_plus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='salario plus'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='salario_escala',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='salario_jornada_laboral',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='salario por jornada laboral'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='salario_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='salario total'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Nombre inválido. Debe comenzar con mayúscula y no puede contener números ni caracteres especiales.', regex='^[A-Z]{1}[A-Za-záéíóúñ .]+$')]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=('M', 'Masculino'), max_length=1),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='t_contrato',
            field=models.CharField(choices=[('1', 'Nombramiento'), ('2', 'Indeterminado'), ('3', 'Determinado por tiempo definido'), ('4', 'Adiestramiento'), ('5', 'Disponible'), ('6', 'A prueba'), ('7', 'Determinado por sustitución de trabajador')], max_length=20, verbose_name='tipo de contrato'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='t_pago',
            field=models.CharField(choices=[('S', 'A tiempo'), ('V', 'Por rendimiento')], max_length=20, verbose_name='tipo de pago'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='t_plantilla',
            field=models.CharField(blank=True, choices=[('A', 'Administrativo'), ('P', 'Productivo')], max_length=15, verbose_name='tipo de plantilla'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='unidad_militar',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='unidad_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trabajadores', to='adm.UnidadOrg', verbose_name='unidad organizacional'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='usuario',
            field=models.CharField(blank=True, default='Ninguno', max_length=20, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Usuario inválido. El valor no puede contener espacios.', regex=' ')], verbose_name='usuario'),
        ),
    ]
